.\" Process this file with
.\" groff -man -Tascii ailurus.1
.\"
.TH AILURUS 1 "MARCH 2010" Linux "User Manuals"
.SH NAME
Ailurus \- a simple application installer and GNOME tweaker
.SH SYNOPSIS
.B ailurus [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Ailurus
is a simple application installer and GNOME tweaker which makes Linux easier to use. It supports Fedora, Ubuntu, ArchLinux and Mint.
.SH BUGS
Please report all bugs to the Ailurus bug tracker:
http://code.google.com/p/ailurus/issues/list

Copyright 2007-2010. Licensed under GPL, version 2 or higher version.
