.\" Process this file with
.\" groff -man -Tascii ailurus.1
.\"
.TH AILURUS 1 "MARCH 2010" Linux "User Manuals"
.SH NAME
Ailurus \- makes Linux easier to use
.SH SYNOPSIS
.B ailurus [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Ailurus
is open source software making Linux easier to use. It supports Fedora, Ubuntu, and Mint.
.SH BUGS
Please report all bugs to the Ailurus bug tracker:
http://code.google.com/p/ailurus/issues/list
.SH AUTHOR
Homer Xing <homer.xing@gmail.com>
CHEN Yangyang <skabyy@gmail.com>
Starboy Qi <starboy.qi@gmail.com>
MA Yue <velly.empire@gmail.com>

Copyright 2007-2010. Licensed under GPL, version 2 or higher version.
