#!/bin/bash 
# 
# This script is in order to help developers uninstall Ailurus clean
# Author : Devil Wang
# Date   : Fri May 14
#

if [ -f "installed_files" ];then
    cat installed_files | xargs rm -rf
    echo "Uninstall completed"
else
    echo "Uninstall Failure, Log did not exist"
fi