#!/bin/bash

find . -type f -exec chmod 644 \{\} \;

chmod 755 bin/ailurus \
          ailurus/main.py \
          developer/* \
          setup.py \
          support/ailurus-daemon \
          support/show-a-linux-skill-bubble \
          uninstall
