#!/bin/bash
if [ $# == 0 ] ; then
	echo "Usage: mplayer_comic vod://202.120.2.244:1680/N:\\avi.avi ./srt.srt"
elif [ $# == 1 ] ; then
	/usr/local/bin/gmplayer `convert_vod_url "$1" | iconv -f utf8 -t gbk`
elif [ $# == 2 ] ; then
	/usr/local/bin/gmplayer -sub "$2" `convert_vod_url "$1" | iconv -f utf8 -t gbk`
fi

