#!/bin/bash
#将Latex文件编译成PDF
#用法：texpdf a.tex   编译当前目录中的a.tex，生成a.pdf，自动打开pdf。
#compile using texlive-2008
#call latex twice for re-making link.
#use bibtex to generate .bbl
#then execute evince to read the pdf.
#使用dvipdfmx，生成的中文pdf体积小
#使用TeX Backward Search
fn=$1
fn=${fn%'.tex'}
latex --src-specials $fn.tex && latex --src-specials $fn.tex && dvipdfmx $fn.dvi && rm $fn.nav $fn.snm $fn.blg $fn.aux $fn.log texput.log $fn.out $fn.toc -f && (evince $fn.pdf &)
